Repository TanmayKalra09/SmartLog, pull requests merged in 2025-07, with the labels that each got.

#18 feat: Initial Backend Implementation: User Authentication with JWT and MongoDB
  server/.env.sample
  server/.gitignore
  server/app.js
  server/controllers/user.controllers.js
  server/db/index.js
  server/index.js
  server/middlewares/auth.middleware.js
  server/models/user.models.js
  server/package-lock.json
  server/package.json
  server/routers/user.routers.js
  server/utils/ApiError.js
  server/utils/ApiResponse.js
  server/utils/asyncHandler.js
Labels: Level 3, gssoc25

#20 Added Footer
  package-lock.json
  package.json
  src/components/Dashboard.jsx
  src/components/Footer.jsx
  src/components/HomePage.jsx
Labels: Level 1, gssoc25

#21 Feat: Add confirmation modal and update dependencies
  package-lock.json
  package.json
  src/components/ConfirmationModal.jsx
  src/components/Dashboard.jsx
  vite.config.js
Labels: enhancement, Level 1, gssoc25

#93 fix: Add error handling for transaction toast notification
  src/components/AddTransactionModal.jsx
Labels: good first issue, Level 1, gssoc25

#99 Goals
  README.md
  package-lock.json
  package.json
  src/App.jsx
  src/components/AddGoalModal.jsx
  src/components/ContributeToGoalModal.jsx
  src/components/Dashboard.jsx
  src/components/GoalCard.jsx
  src/components/GoalsPage.jsx
  src/components/TransactionContext.jsx
Labels: good first issue, Level 3, gssoc25
